spring.datasource.url=jdbc:postgresql://localhost:5432/bd_tfg
spring.datasource.username=postgres
spring.datasource.password=4lt41r
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#####################################################################################
#Configuracion de puerto del servidor por si nos da problemas o para aumentar la robustez de la config
server.port=8081
####################################################################################
# Desactivar CSRF
spring.security.csrf.enabled=false

##################################################################################
#Configuración para el envio de correo de verificación de la cuenta
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=Osteologia2@gmail.com
spring.mail.password=qxse dbyv cles lduy
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
####################################################################################
#Configuración para token de expiración
token.expiration.minutes=15

#############################################################################
#Configuracion para los ficheros log
# Log level configuration
logging.level.org.springframework.web=INFO
logging.level.com.estadisticas=DEBUG

# Define log file name and location
logging.file.name=logs/estadisticas_app.log

# Define log pattern (optional)
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

#Cuando el archivo alcance 10 MB, se creará un nuevo archivo.
logging.logback.rollingpolicy.max-file-size=10MB

#Se mantendrán los logs de los últimos 7 días o rotaciones.
logging.logback.rollingpolicy.max-history=7

###########################################################
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

